# Generated by Django 4.2.4 on 2023-08-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('id', 'name'), 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
    ]
