# Generated by Django 4.2.4 on 2023-08-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название')),
                ('color', models.CharField(max_length=6, verbose_name='Цвет(HEX)')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('id', 'name'),
            },
        ),
    ]
