# Generated by Django 4.2.4 on 2023-08-10 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_alter_recipe_name_alter_recipe_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_recipe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites2', to='recipes.recipe', verbose_name='Избранные рецепты')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
            },
        ),
        migrations.AddConstraint(
            model_name='favorite2',
            constraint=models.UniqueConstraint(fields=('user2', 'favorite_recipe2'), name='unique_user_and_favorite_recipe2'),
        ),
    ]
