# Generated by Django 4.2.4 on 2023-08-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_buylist_recipe_alter_buylist_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='buylist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_and_buylist_recipe'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_and_favorite_recipe'),
        ),
    ]
