# Generated by Django 4.2.4 on 2023-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_ingredient_unique_ingredient_measurement_units_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient', violation_error_message='Этот ингредиент уже есть в рецепте.'),
        ),
    ]
