# Generated by Django 4.2.4 on 2023-08-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_buylist_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='measurement_unit',
        ),
    ]
