# Generated by Django 4.2.4 on 2023-08-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='user!=author',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_name_and_author',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('author')), _negated=True), name='user!=author', violation_error_message='Нельзя подписываться на себя.'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_name_and_author', violation_error_message='Эта подписка уже есть. '),
        ),
    ]
